### ISSUE TITLE
发布到 jitpack

### ISSUE THREAD

**Issue by tiann** [GitLqr/LQRLibyuv#7]
直接用文件依赖很不方便，建议放到 jitpack 上去。我在 jitpack 上生成了一个，目前可以按照如下方式依赖：

```
implementation 'com.github.GitLqr:LQRLibyuv:701bfb84c0'
```

后面那个奇怪的版本号是当前的 git commit 记录。

可以有两种方式：

1. 在 git 上创建一个 tag，比如：1.0.0
2. 在 github 的 release 页面发布一个版本：https://github.com/GitLqr/LQRLibyuv/releases

**Comment by GitLqr** [comment]
已发布 jitpack
